//////////////////////////////////////////////////////////////////////////////
// File:  ./bsp.h
//
// This file has been generated automatically by QP Modeler (QM).
// DO NOT EDIT THIS FILE MANUALLY.
//
// Please visit www.state-machine.com/qm for more information.
//////////////////////////////////////////////////////////////////////////////
#ifndef bsp_h
#define bsp_h

#include <avr/io.h>  // AVR I/O
#include "realSwitches.hpp"
#include "realMotor.hpp"

// Sys timer tick per seconds
#define BSP_TICKS_PER_SEC    100


void BSP_init(void);
void BSP_display(char const *msg);
void BSP_display(char *msg);
void BSP_addSwitchEvent(uint16_t sig);
void BSP_addMotorEvent(uint16_t sig);
void BSP_dispatchSwitchEvent(void);
void BSP_dispatchMotorEvent(void);

extern RealSwitches realSwitches;
extern RealMotor realMotor;


/////////////////////////////////////////////////////////////////////
// NOTE: The CPU clock frequency F_CPU is defined externally for each
// Arduino board

#endif  // bsp_h

